const C = window.WAREHOUSE_CONFIG;
const configured = C.SUPABASE_URL?.startsWith('http') && !C.SUPABASE_URL.includes('PASTE') && C.SUPABASE_ANON_KEY && !C.SUPABASE_ANON_KEY.includes('PASTE');
const sb = configured ? supabase.createClient(C.SUPABASE_URL, C.SUPABASE_ANON_KEY) : null;
let products = [], activities = [], user = null, isAdmin = false, currentPage = 'dashboard', realtimeChannel = null;
const $ = id => document.getElementById(id); const view = $('view');
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const safeImg = s => s && /^https?:\/\//i.test(s) ? s : 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1000&q=85';
function toast(msg, kind=''){ const t=$('toast'); t.textContent=msg; t.className='toast show '+kind; clearTimeout(window.__toast); window.__toast=setTimeout(()=>t.className='toast',3200); }
function setBusy(btn,busy,label='Saving…'){btn.disabled=busy;if(busy)btn.dataset.old=btn.textContent,btn.textContent=label;else btn.textContent=btn.dataset.old||btn.textContent;}
async function boot(){
  if(!sb){renderSetup();return;}
  setConnection(false);
  const session = await sb.auth.getSession(); user=session.data.session?.user||null; await refreshAuth();
  sb.auth.onAuthStateChange(async (_e,s)=>{user=s?.user||null; await refreshAuth(); render();});
  subscribeRealtime(); await loadAll(); render();
}
function setConnection(ok){$('liveDot').classList.toggle('offline',!ok);$('liveDot').title=ok?'Live database connection':'Connecting / offline';}
async function refreshAuth(){ isAdmin=false; if(user){ const r=await sb.from('admin_users').select('user_id').eq('user_id',user.id).maybeSingle(); isAdmin=!!r.data && !r.error; } updateAuth(); }
function updateAuth(){ $('hello').textContent=user?(isAdmin?`Admin • ${user.email}`:`Signed in • ${user.email}`):'Public view'; $('logout').classList.toggle('hidden',!user); }
async function loadAll(){
  const [p,a]=await Promise.all([sb.from('products').select('*').order('created_at',{ascending:false}),sb.from('activity').select('*').order('created_at',{ascending:false}).limit(60)]);
  if(p.error) toast(p.error.message,'error'); else products=p.data||[];
  if(!a.error) activities=a.data||[];
}
function subscribeRealtime(){
  realtimeChannel=sb.channel('warehouse-live').on('postgres_changes',{event:'*',schema:'public',table:'products'},async()=>{await loadAll();render();setConnection(true);}).on('postgres_changes',{event:'*',schema:'public',table:'activity'},async()=>{const a=await sb.from('activity').select('*').order('created_at',{ascending:false}).limit(60);activities=a.data||[];if(currentPage==='activity')render();setConnection(true);}).subscribe(status=>setConnection(status==='SUBSCRIBED'));
}
function renderSetup(){view.innerHTML=`<section class="hero"><span class="eyebrow">ONE-TIME SETUP</span><h1>Connect your<br>warehouse.</h1><p>This build is ready for GitHub Pages + Supabase Free. Add the two Supabase values in <b>config.js</b>, run <b>schema.sql</b>, create your admin account, then add its user ID to <b>admin_users</b>.</p><div class="setup-grid"><div class="panel glass"><b>01</b><h3>Create Supabase</h3><p>Free project, Auth, Database and Storage.</p></div><div class="panel glass"><b>02</b><h3>Run schema.sql</h3><p>Creates tables, RLS, storage and live updates.</p></div><div class="panel glass"><b>03</b><h3>Deploy GitHub Pages</h3><p>No paid server is required.</p></div></div></section>`}
function render(){ document.querySelectorAll('.sidebar nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===currentPage)); if(currentPage==='dashboard')dashboard(); if(currentPage==='inventory')inventory(); if(currentPage==='activity')activity(); if(currentPage==='admin')admin(); }
function dashboard(){
 const total=products.reduce((n,p)=>n+p.quantity,0), low=products.filter(p=>p.quantity<=7).length, cats=new Set(products.map(p=>p.category)).size, locs=new Set(products.map(p=>p.location)).size;
 view.innerHTML=`<section class="hero"><span class="eyebrow">WAREHOUSE • LIVE OVERVIEW</span><h1>Everything<br>in one place.</h1><p>Live inventory for everyone. Management stays private to approved administrator accounts.</p><button class="primary" onclick="go('inventory')">Browse inventory →</button></section>
 <section class="stats"><div class="stat glass"><small>Total units</small><b>${total}</b><span>across all items</span></div><div class="stat glass"><small>Products</small><b>${products.length}</b><span>unique items</span></div><div class="stat glass"><small>Low stock</small><b>${low}</b><span>7 units or less</span></div><div class="stat glass"><small>Locations</small><b>${locs}</b><span>${cats} categories</span></div></section>
 <section class="content"><div class="panel glass"><div class="head"><h2>Recently added</h2><span class="muted">Live</span></div>${products.slice(0,6).map(itemRow).join('')||empty('No items yet.','Add your first item from Admin.')}</div><div class="panel glass"><div class="head"><h2>Inventory health</h2><span class="muted">${low?low+' need attention':'All good'}</span></div><div class="activity">${products.filter(p=>p.quantity<=7).slice(0,6).map(p=>`<div><i class="dot"></i><p><b>${esc(p.name)}</b><small>${p.quantity} units left • ${esc(p.location)}</small></p></div>`).join('')||'<p class="muted">All stock levels look good.</p>'}</div></div></section>`;
}
function itemRow(p){return `<div class="item"><img class="thumb" src="${safeImg(p.image_url)}" onerror="this.src='${safeImg('')}'"><div class="itemmain"><b>${esc(p.name)}</b><span>${esc(p.category)} • ${esc(p.location)}</span></div><strong>${p.quantity} pcs</strong><span class="badge ${p.quantity<=7?'low':''}">${p.quantity<=7?'Low stock':'In stock'}</span></div>`}
function inventory(){
 const cats=[...new Set(products.map(p=>p.category).filter(Boolean))].sort(),locs=[...new Set(products.map(p=>p.location).filter(Boolean))].sort();
 view.innerHTML=`<section class="hero compact"><span class="eyebrow">PUBLIC INVENTORY</span><h1>What we<br>have.</h1><p>Everyone can browse the current warehouse stock. ${isAdmin?'You are signed in as administrator.':''}</p></section><section class="panel glass"><div class="head wrap"><div><h2>All items <span class="muted">${products.length} products</span></h2></div><div class="filters"><input id="filter" class="search" placeholder="Search name, category, location…"><select id="catFilter"><option value="">All categories</option>${cats.map(x=>`<option>${esc(x)}</option>`).join('')}</select><select id="locFilter"><option value="">All locations</option>${locs.map(x=>`<option>${esc(x)}</option>`).join('')}</select></div></div><div id="cards" class="cards">${cards(products)}</div></section>`;
 const apply=()=>{const q=$('filter').value.toLowerCase(),c=$('catFilter').value,l=$('locFilter').value; $('cards').innerHTML=cards(products.filter(p=>(`${p.name} ${p.description} ${p.category} ${p.location}`).toLowerCase().includes(q)&&(!c||p.category===c)&&(!l||p.location===l)));};
 $('filter').oninput=apply;$('catFilter').onchange=apply;$('locFilter').onchange=apply;
}
function cards(arr){return arr.map(p=>`<article class="product glass"><div class="imgwrap"><img src="${safeImg(p.image_url)}" onerror="this.src='${safeImg('')}'"><span class="stock-dot ${p.quantity<=7?'warn':''}"></span></div><div class="body"><div class="product-meta"><span>${esc(p.category)}</span><span>${esc(p.location)}</span></div><h3>${esc(p.name)}</h3><p>${esc(p.description||'No description')}</p><div class="foot"><b>${p.quantity} pcs</b><span class="badge ${p.quantity<=7?'low':''}">${p.quantity<=7?'Low stock':'In stock'}</span></div>${isAdmin?`<div class="actions"><button class="smallbtn" onclick="editProduct('${p.id}')">Edit</button><button class="smallbtn danger" onclick="deleteProduct('${p.id}')">Delete</button></div>`:''}</div></article>`).join('')||empty('No products found.','Try another search or filter.');}
function activity(){view.innerHTML=`<section class="hero compact"><span class="eyebrow">LIVE AUDIT TRAIL</span><h1>Warehouse<br>history.</h1><p>Product creates, edits and deletes are recorded automatically by the database.</p></section><section class="panel glass"><div class="head"><h2>Recent activity</h2><span class="muted">${activities.length} events</span></div><div class="timeline">${activities.map(a=>`<div class="timeline-row"><div class="timeline-icon">${a.action==='created'?'+':a.action==='deleted'?'×':'↻'}</div><div><b>${esc(a.product_name)}</b><p>${esc(a.action)} ${a.actor_email?`by ${esc(a.actor_email)}`:''}</p></div><time>${timeAgo(a.created_at)}</time></div>`).join('')||empty('No activity yet.','Changes will appear here automatically.')}</div></section>`}
function admin(){if(!isAdmin){view.innerHTML=`<section class="hero"><span class="eyebrow">PRIVATE AREA</span><h1>Admin<br>access.</h1><p>Visitors can browse inventory. Only an account approved in <b>admin_users</b> can manage it.</p><button class="primary" onclick="loginDialog.showModal()">Sign in →</button></section>`;return;} view.innerHTML=`<section class="hero compact"><span class="eyebrow">ADMIN • ${esc(user.email)}</span><h1>Control the<br>warehouse.</h1><p>Changes are protected by Supabase Row Level Security and appear live for visitors.</p><button class="primary" onclick="openAdd()">＋ Add item</button></section><section class="panel glass"><div class="head"><h2>Manage inventory</h2><span class="muted">${products.length} items</span></div>${products.map(p=>`<div class="item admin-row"><img class="thumb" src="${safeImg(p.image_url)}"><div class="itemmain"><b>${esc(p.name)}</b><span>${p.quantity} pcs • ${esc(p.location)} • ${esc(p.category)}</span></div><button class="smallbtn" onclick="editProduct('${p.id}')">Edit</button><button class="smallbtn danger" onclick="deleteProduct('${p.id}')">Delete</button></div>`).join('')||empty('No items yet.','Add your first item above.')}</section>`}
function empty(title,sub){return `<div class="empty"><strong>${esc(title)}</strong><span>${esc(sub)}</span></div>`}
function go(page){currentPage=page;render()}
function timeAgo(date){const s=Math.max(1,(Date.now()-new Date(date).getTime())/1000);if(s<60)return `${Math.round(s)}s ago`;if(s<3600)return `${Math.round(s/60)}m ago`;if(s<86400)return `${Math.round(s/3600)}h ago`;return new Date(date).toLocaleDateString();}
function openAdd(){if(!isAdmin)return loginDialog.showModal();$('productForm').reset();$('productId').value='';$('formTitle').textContent='Add item';$('formMsg').textContent='';$('imagePreview').classList.add('hidden');productDialog.showModal()}
function editProduct(id){const p=products.find(x=>x.id===id);if(!p||!isAdmin)return;$('productId').value=p.id;$('pName').value=p.name;$('pDesc').value=p.description||'';$('pQty').value=p.quantity;$('pLoc').value=p.location;$('pCat').value=p.category||'General';$('pPrice').value=p.price||0;$('pImage').value=p.image_url||'';$('pImageFile').value='';$('formTitle').textContent='Edit item';$('formMsg').textContent='';preview(p.image_url);productDialog.showModal()}
function preview(url){const el=$('imagePreview');if(!url){el.classList.add('hidden');return;}el.innerHTML=`<img src="${safeImg(url)}"><span>Current image</span>`;el.classList.remove('hidden')}
async function uploadImage(file){if(!file)return '';if(!/^image\/(png|jpeg|webp|gif)$/.test(file.type))throw Error('Please choose a PNG, JPG, WEBP or GIF image.');if(file.size>5*1024*1024)throw Error('Image is larger than 5 MB. Please compress it first.');const ext=file.name.split('.').pop().toLowerCase();const path=`${user.id}/${crypto.randomUUID()}.${ext}`;const up=await sb.storage.from(C.STORAGE_BUCKET).upload(path,file,{upsert:false,contentType:file.type});if(up.error)throw up.error;return sb.storage.from(C.STORAGE_BUCKET).getPublicUrl(path).data.publicUrl;}
async function deleteProduct(id){if(!isAdmin||!confirm('Delete this item? This action is recorded in the activity log.'))return;const {error}=await sb.from('products').delete().eq('id',id);if(error){toast(error.message,'error');return;}toast('Item deleted');await loadAll();render()}
$('productForm').onsubmit=async e=>{e.preventDefault();if(!isAdmin)return;const btn=$('saveProduct');setBusy(btn,true);$('formMsg').textContent='';try{let image=$('pImage').value.trim();const file=$('pImageFile').files[0];if(file)image=await uploadImage(file);const payload={name:$('pName').value.trim(),description:$('pDesc').value.trim(),quantity:+$('pQty').value,location:$('pLoc').value.trim(),category:$('pCat').value.trim()||'General',price:+$('pPrice').value||0,image_url:image};const id=$('productId').value;const result=id?await sb.from('products').update(payload).eq('id',id):await sb.from('products').insert(payload);if(result.error)throw result.error;productDialog.close();toast(id?'Item updated':'Item added');await loadAll();render();}catch(err){$('formMsg').textContent=err.message||String(err);}finally{setBusy(btn,false)}};
$('loginForm').onsubmit=async e=>{e.preventDefault();const btn=$('loginSubmit');setBusy(btn,true,'Signing in…');$('loginMsg').textContent='';const r=await sb.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(r.error){$('loginMsg').textContent=r.error.message;setBusy(btn,false);return;}loginDialog.close();toast('Signed in');setBusy(btn,false);};
$('logout').onclick=async()=>{await sb.auth.signOut();toast('Signed out');};
document.querySelectorAll('.sidebar nav button').forEach(b=>b.onclick=()=>go(b.dataset.page));$('searchBtn').onclick=()=>{go('inventory');setTimeout(()=>$('filter')?.focus(),50)};$('pImageFile').onchange=e=>{const f=e.target.files[0];if(f){const url=URL.createObjectURL(f);preview(url)}};
boot();
