window.WAREHOUSE_CONFIG = {
  SUPABASE_URL: "PASTE_YOUR_SUPABASE_URL",
  SUPABASE_ANON_KEY: "PASTE_YOUR_SUPABASE_ANON_OR_PUBLISHABLE_KEY",
  ADMIN_EMAIL: "admin@warehouse.com",
  STORAGE_BUCKET: "product-images"
};
