-- WAREHOUSE / FREE SUPABASE SETUP
-- Run this whole file in Supabase SQL Editor.
-- After creating your admin user in Authentication, run the final INSERT shown in the README.

create extension if not exists pgcrypto;

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text not null default '',
  quantity integer not null default 0 check (quantity >= 0),
  location text not null default 'A-01',
  category text not null default 'General',
  price numeric(12,2) not null default 0 check (price >= 0),
  image_url text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.activity (
  id bigint generated by default as identity primary key,
  product_id uuid references public.products(id) on delete set null,
  action text not null check (action in ('created','updated','deleted')),
  product_name text not null,
  actor_email text not null default '',
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.admin_users enable row level security;
alter table public.activity enable row level security;

-- Helper: is the signed-in user an admin?
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.admin_users a where a.user_id = auth.uid());
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

-- PRODUCTS: everyone can read, admins can write.
drop policy if exists "public can view products" on public.products;
create policy "public can view products" on public.products for select using (true);

drop policy if exists "admins can insert products" on public.products;
create policy "admins can insert products" on public.products for insert to authenticated with check (public.is_admin());

drop policy if exists "admins can update products" on public.products;
create policy "admins can update products" on public.products for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admins can delete products" on public.products;
create policy "admins can delete products" on public.products for delete to authenticated using (public.is_admin());

-- ADMIN_USERS: an admin can see only their own membership.
drop policy if exists "admins can read own admin row" on public.admin_users;
create policy "admins can read own admin row" on public.admin_users for select to authenticated using (user_id = auth.uid());

-- ACTIVITY: everyone can read; only admins can manually insert (triggers insert automatically).
drop policy if exists "public can view activity" on public.activity;
create policy "public can view activity" on public.activity for select using (true);

drop policy if exists "admins can insert activity" on public.activity;
create policy "admins can insert activity" on public.activity for insert to authenticated with check (public.is_admin());

-- Keep updated_at current.
create or replace function public.touch_product()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_touch on public.products;
create trigger products_touch before update on public.products
for each row execute function public.touch_product();

-- Automatic audit trail. This means the browser does not need to be trusted to write logs.
create or replace function public.log_product_activity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.activity(product_id, action, product_name, actor_email)
    values (new.id, 'created', new.name, coalesce(auth.jwt()->>'email',''));
    return new;
  elsif tg_op = 'UPDATE' then
    insert into public.activity(product_id, action, product_name, actor_email)
    values (new.id, 'updated', new.name, coalesce(auth.jwt()->>'email',''));
    return new;
  elsif tg_op = 'DELETE' then
    insert into public.activity(product_id, action, product_name, actor_email)
    values (old.id, 'deleted', old.name, coalesce(auth.jwt()->>'email',''));
    return old;
  end if;
  return null;
end;
$$;

drop trigger if exists products_activity on public.products;
create trigger products_activity after insert or update or delete on public.products
for each row execute function public.log_product_activity();

-- Seed only when empty. Delete these rows later if you want a clean warehouse.
insert into public.products(name,description,quantity,location,category,price,image_url)
select * from (values
('Office Chair','Ergonomic black office chair',24,'A-12','Furniture',120.00,'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=1000&q=85'),
('LED Desk Lamp','Adjustable desk lamp',41,'B-04','Electronics',39.00,'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1000&q=85'),
('Storage Box','Medium stackable storage box',6,'C-18','Storage',12.50,'https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=1000&q=85')
) as v(name,description,quantity,location,category,price,image_url)
where not exists (select 1 from public.products);

-- STORAGE: public bucket for image viewing. Upload/delete are admin-only.
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = true;

drop policy if exists "public can view product images" on storage.objects;
create policy "public can view product images" on storage.objects
for select using (bucket_id = 'product-images');

drop policy if exists "admins can upload product images" on storage.objects;
create policy "admins can upload product images" on storage.objects
for insert to authenticated with check (bucket_id = 'product-images' and public.is_admin());

drop policy if exists "admins can update product images" on storage.objects;
create policy "admins can update product images" on storage.objects
for update to authenticated using (bucket_id = 'product-images' and public.is_admin()) with check (bucket_id = 'product-images' and public.is_admin());

drop policy if exists "admins can delete product images" on storage.objects;
create policy "admins can delete product images" on storage.objects
for delete to authenticated using (bucket_id = 'product-images' and public.is_admin());

-- Realtime is enabled separately in Supabase Dashboard -> Database -> Replication.
-- This avoids duplicate-publication errors when a table is already enabled.
