-- WAREHOUSE / FREE SUPABASE SETUP
-- Run this whole file in Supabase SQL Editor.
-- After creating your admin user in Authentication, run the final INSERT shown in the README.

create extension if not exists pgcrypto;

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text not null default '',
  quantity integer not null default 0 check (quantity >= 0),
  location text not null default 'A-01',
  category text not null default 'General',
  price numeric(12,2) not null default 0 check (price >= 0),
  image_url text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.activity (
  id bigint generated by default as identity primary key,
  product_id uuid references public.products(id) on delete set null,
  action text not null check (action in ('created','updated','deleted')),
  product_name text not null,
  actor_email text not null default '',
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.admin_users enable row level security;
alter table public.activity enable row level security;

-- Helper: is the signed-in user an admin?
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.admin_users a where a.user_id = auth.uid());
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

-- PRODUCTS: everyone can read, admins can write.
drop policy if exists "public can view products" on public.products;
create policy "public can view products" on public.products for select using (true);

drop policy if exists "admins can insert products" on public.products;
create policy "admins can insert products" on public.products for insert to authenticated with check (public.is_admin());

drop policy if exists "admins can update products" on public.products;
create policy "admins can update products" on public.products for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admins can delete products" on public.products;
create policy "admins can delete products" on public.products for delete to authenticated using (public.is_admin());

-- ADMIN_USERS: an admin can see only their own membership.
drop policy if exists "admins can read own admin row" on public.admin_users;
create policy "admins can read own admin row" on public.admin_users for select to authenticated using (user_id = auth.uid());

-- ACTIVITY: everyone can read; only admins can manually insert (triggers insert automatically).
drop policy if exists "public can view activity" on public.activity;
create policy "public can view activity" on public.activity for select using (true);

drop policy if exists "admins can insert activity" on public.activity;
create policy "admins can insert activity" on public.activity for insert to authenticated with check (public.is_admin());

-- Keep updated_at current.
create or replace function public.touch_product()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_touch on public.products;
create trigger products_touch before update on public.products
for each row execute function public.touch_product();

-- Automatic audit trail. This means the browser does not need to be trusted to write logs.
create or replace function public.log_product_activity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.activity(product_id, action, product_name, actor_email)
    values (new.id, 'created', new.name, coalesce(auth.jwt()->>'email',''));
    return new;
  elsif tg_op = 'UPDATE' then
    insert into public.activity(product_id, action, product_name, actor_email)
    values (new.id, 'updated', new.name, coalesce(auth.jwt()->>'email',''));
    return new;
  elsif tg_op = 'DELETE' then
    insert into public.activity(product_id, action, product_name, actor_email)
    values (old.id, 'deleted', old.name, coalesce(auth.jwt()->>'email',''));
    return old;
  end if;
  return null;
end;
$$;

drop trigger if exists products_activity on public.products;
create trigger products_activity after insert or update or delete on public.products
for each row execute function public.log_product_activity();

-- Seed only when empty. Delete these rows later if you want a clean warehouse.
insert into public.products(name,description,quantity,location,category,price,image_url)
select * from (values
('Office Chair','Ergonomic black office chair',24,'A-12','Furniture',120.00,'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=1000&q=85'),
('LED Desk Lamp','Adjustable desk lamp',41,'B-04','Electronics',39.00,'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1000&q=85'),
('Storage Box','Medium stackable storage box',6,'C-18','Storage',12.50,'https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=1000&q=85')
) as v(name,description,quantity,location,category,price,image_url)
where not exists (select 1 from public.products);

-- STORAGE: public bucket for image viewing. Upload/delete are admin-only.
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = true;

drop policy if exists "public can view product images" on storage.objects;
create policy "public can view product images" on storage.objects
for select using (bucket_id = 'product-images');

drop policy if exists "admins can upload product images" on storage.objects;
create policy "admins can upload product images" on storage.objects
for insert to authenticated with check (bucket_id = 'product-images' and public.is_admin());

drop policy if exists "admins can update product images" on storage.objects;
create policy "admins can update product images" on storage.objects
for update to authenticated using (bucket_id = 'product-images' and public.is_admin()) with check (bucket_id = 'product-images' and public.is_admin());

drop policy if exists "admins can delete product images" on storage.objects;
create policy "admins can delete product images" on storage.objects
for delete to authenticated using (bucket_id = 'product-images' and public.is_admin());

-- Realtime is enabled separately in Supabase Dashboard -> Database -> Replication.
-- This avoids duplicate-publication errors when a table is already enabled.


-- ============================================================
-- DELIVERY WORKFLOW / SERIALIZED INVENTORY
-- Run this section after the original schema.
-- ============================================================

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  role text not null default 'delivery_guy' check (role in ('admin','delivery_guy')),
  created_at timestamptz not null default now()
);

create table if not exists public.inventory_units (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  serial_number text not null unique,
  status text not null default 'available' check (status in ('available','reserved','out_for_delivery','delivered')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.delivery_requests (
  id uuid primary key default gen_random_uuid(),
  delivery_guy_id uuid not null references auth.users(id) on delete restrict,
  product_id uuid not null references public.products(id) on delete restrict,
  unit_id uuid not null references public.inventory_units(id) on delete restrict,
  destination text not null,
  recipient text not null default '',
  delivery_date date not null,
  notes text not null default '',
  status text not null default 'pending_admin_approval' check (status in ('pending_admin_approval','approved_for_delivery','delivery_note_submitted','completed','rejected')),
  delivery_note_url text not null default '',
  delivery_note_number text not null default '',
  driver_notes text not null default '',
  rejection_reason text not null default '',
  created_at timestamptz not null default now(),
  approved_at timestamptz,
  delivered_at timestamptz,
  completed_at timestamptz,
  approved_by uuid references auth.users(id),
  completed_by uuid references auth.users(id)
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  recipient_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  body text not null default '',
  type text not null default 'delivery',
  reference_id uuid,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.inventory_units enable row level security;
alter table public.delivery_requests enable row level security;
alter table public.notifications enable row level security;

create or replace function public.is_delivery()
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='delivery_guy');
$$;

revoke all on function public.is_delivery() from public;
grant execute on function public.is_delivery() to anon, authenticated;

drop policy if exists "users can read own profile" on public.profiles;
create policy "users can read own profile" on public.profiles for select to authenticated using (id=auth.uid());

drop policy if exists "public can read units" on public.inventory_units;
create policy "public can read units" on public.inventory_units for select using (true);

drop policy if exists "admins can manage units" on public.inventory_units;
create policy "admins can manage units" on public.inventory_units for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "delivery can read own requests" on public.delivery_requests;
create policy "delivery can read own requests" on public.delivery_requests for select to authenticated using (delivery_guy_id=auth.uid() or public.is_admin());

drop policy if exists "delivery can create requests" on public.delivery_requests;
create policy "delivery can create requests" on public.delivery_requests for insert to authenticated with check (delivery_guy_id=auth.uid() and public.is_delivery());

drop policy if exists "delivery can submit notes" on public.delivery_requests;
create policy "delivery can submit notes" on public.delivery_requests for update to authenticated using (delivery_guy_id=auth.uid() and status='approved_for_delivery') with check (delivery_guy_id=auth.uid() and status='delivery_note_submitted');

drop policy if exists "admins can update deliveries" on public.delivery_requests;
create policy "admins can update deliveries" on public.delivery_requests for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "users can read own notifications" on public.notifications;
create policy "users can read own notifications" on public.notifications for select to authenticated using (recipient_id=auth.uid());

drop policy if exists "users can mark own notifications" on public.notifications;
create policy "users can mark own notifications" on public.notifications for update to authenticated using (recipient_id=auth.uid()) with check (recipient_id=auth.uid());

-- Delivery accounts may read product details but cannot edit inventory.
-- Admin RPCs perform the critical state changes atomically.

create or replace function public.approve_delivery_request(request_id uuid)
returns public.delivery_requests
language plpgsql
security definer set search_path=public
as $$
declare r public.delivery_requests;
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  select * into r from public.delivery_requests where id=request_id for update;
  if r.id is null then raise exception 'Delivery request not found'; end if;
  if r.status <> 'pending_admin_approval' then raise exception 'Request is not awaiting approval'; end if;

  update public.inventory_units
  set status='reserved', updated_at=now()
  where id=r.unit_id and status='available';
  if not found then raise exception 'This serial number is no longer available'; end if;

  update public.delivery_requests
  set status='approved_for_delivery', approved_at=now(), approved_by=auth.uid()
  where id=request_id returning * into r;

  insert into public.notifications(recipient_id,title,body,type,reference_id)
  values(r.delivery_guy_id,'Delivery approved',
         'Your delivery request for serial ' || (select serial_number from public.inventory_units where id=r.unit_id) || ' was approved.',
         'delivery',r.id);

  return r;
end;
$$;

create or replace function public.reject_delivery_request(request_id uuid, rejection_reason text default '')
returns public.delivery_requests
language plpgsql
security definer set search_path=public
as $$
declare r public.delivery_requests;
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  select * into r from public.delivery_requests where id=request_id for update;
  if r.id is null then raise exception 'Delivery request not found'; end if;

  if r.status='approved_for_delivery' or r.status='pending_admin_approval' or r.status='delivery_note_submitted' then
    update public.inventory_units set status='available', updated_at=now()
    where id=r.unit_id and status in ('reserved','out_for_delivery');
  end if;

  update public.delivery_requests
  set status='rejected', rejection_reason=coalesce(rejection_reason,'')
  where id=request_id returning * into r;

  insert into public.notifications(recipient_id,title,body,type,reference_id)
  values(r.delivery_guy_id,'Delivery rejected',
         'Your delivery request was rejected.' || case when coalesce(rejection_reason,'')<>'' then ' Reason: '||rejection_reason else '' end,
         'delivery',r.id);
  return r;
end;
$$;

create or replace function public.complete_delivery_request(request_id uuid)
returns public.delivery_requests
language plpgsql security definer set search_path=public
as $$
declare r public.delivery_requests;
declare p public.products;
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  select * into r from public.delivery_requests where id=request_id for update;
  if r.id is null then raise exception 'Delivery request not found'; end if;
  if r.status <> 'delivery_note_submitted' then raise exception 'Delivery note must be submitted first'; end if;

  update public.inventory_units set status='delivered', updated_at=now()
  where id=r.unit_id and status in ('reserved','out_for_delivery');
  if not found then raise exception 'Inventory unit is not reserved'; end if;

  update public.products set quantity=greatest(0,quantity-1), updated_at=now()
  where id=r.product_id returning * into p;

  update public.delivery_requests
  set status='completed', completed_at=now(), completed_by=auth.uid()
  where id=request_id returning * into r;

  insert into public.notifications(recipient_id,title,body,type,reference_id)
  values(r.delivery_guy_id,'Delivery completed',
         'Delivery for serial ' || (select serial_number from public.inventory_units where id=r.unit_id) || ' was completed successfully.',
         'delivery',r.id);
  return r;
end;
$$;

grant execute on function public.approve_delivery_request(uuid) to authenticated;
grant execute on function public.reject_delivery_request(uuid,text) to authenticated;
grant execute on function public.complete_delivery_request(uuid) to authenticated;

-- Trigger: new request -> notify every admin.
create or replace function public.notify_new_delivery()
returns trigger language plpgsql security definer set search_path=public as $$
declare a record;
begin
  for a in select user_id from public.admin_users loop
    insert into public.notifications(recipient_id,title,body,type,reference_id)
    values(a.user_id,'New delivery request',
      'A delivery request for serial ' || (select serial_number from public.inventory_units where id=new.unit_id) ||
      ' was submitted for ' || new.destination || '.','delivery',new.id);
  end loop;
  return new;
end;
$$;

drop trigger if exists delivery_request_notify on public.delivery_requests;
create trigger delivery_request_notify after insert on public.delivery_requests
for each row execute function public.notify_new_delivery();

create or replace function public.notify_delivery_note()
returns trigger language plpgsql security definer set search_path=public as $$
declare a record;
begin
  if new.status='delivery_note_submitted' and old.status is distinct from new.status then
    for a in select user_id from public.admin_users loop
      insert into public.notifications(recipient_id,title,body,type,reference_id)
      values(a.user_id,'Delivery note submitted',
        'A delivery note is ready for review for serial ' || (select serial_number from public.inventory_units where id=new.unit_id) || '.',
        'delivery',new.id);
    end loop;
  end if;
  return new;
end;
$$;

drop trigger if exists delivery_note_notify on public.delivery_requests;
create trigger delivery_note_notify after update on public.delivery_requests
for each row execute function public.notify_delivery_note();

-- Storage bucket for delivery notes
insert into storage.buckets(id,name,public)
values('delivery-notes','delivery-notes',true)
on conflict(id) do update set public=true;

drop policy if exists "delivery users upload notes" on storage.objects;
create policy "delivery users upload notes" on storage.objects
for insert to authenticated with check (bucket_id='delivery-notes' and public.is_delivery());

drop policy if exists "public can view delivery notes" on storage.objects;
create policy "public can view delivery notes" on storage.objects
for select using (bucket_id='delivery-notes');

-- Optional: create a delivery user after creating an Auth user:
-- insert into public.profiles(id,full_name,role) values('AUTH-USER-UUID','Delivery Guy','delivery_guy');
-- To make an existing admin profile explicit:
-- insert into public.profiles(id,full_name,role) values('ADMIN-AUTH-UUID','Admin','admin')
-- on conflict(id) do update set role='admin';
